project:
  type: website

website:
  title: "Akshat's Blog"
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with a theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)."
    left: "&copy; CC-By Akshat Goel"
 
  navbar:
      right:
        - about.qmd

format:
  html:
    theme: [sandstone, custom.scss]
    mainfont: arial
    fontsize: 1rem
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left



